language: python
python:
  - "2.7"
# command to install dependencies

jdk:
  - oraclejdk7

env:
  - HADOOP_VERSION=0.20.2
  - HADOOP_VERSION=0.20.2-cdh3u4
  - HADOOP_VERSION=0.20.2-cdh3u5
  - HADOOP_VERSION=1.0.4
  - HADOOP_VERSION=1.1.2
  - HADOOP_VERSION = 2.0.0-mr1-cdh4.2.0
  - HADOOP_VERSION = 2.0.0-mr1-cdh4.3.0
  - HADOOP_VERSION = 2.0.0-cdh4.2.0
  - HADOOP_VERSION = 2.0.0-cdh4.3.0
  
  
before_install:
  - sudo apt-get install build-essential python-all-dev libboost-python-dev libssl-dev
  - ssh-keygen -t dsa -P '' -f ~/.ssh/id_dsa 
  - cat ~/.ssh/id_dsa.pub >> ~/.ssh/authorized_keys
  - echo NoHostAuthenticationForLocalhost=yes >> ~/.ssh/config
  - if [[ "$HADOOP_VERSION" != *cdh* ]]; then 
        wget http://archive.apache.org/dist/hadoop/core/hadoop-$HADOOP_VERSION/hadoop-$HADOOP_VERSION.tar.gz; 
        tar xf hadoop-$HADOOP_VERSION.tar.gz;
        export HADOOP_HOME=`pwd`/hadoop-$HADOOP_VERSION;
        $HADOOP_HOME/bin/hadoop namenode -format;
        $HADOOP_HOME/bin/start-all.sh;
        HADOOP_HOME/bin/hadoop dfsadmin -safemode wait;
   fi  
   - if [[ "$HADOOP_VERSION" == *cdh* ]]; then 
        wget http://archive.cloudera.com/cdh4/one-click-install/precise/amd64/cdh4-repository_1.0_all.deb; 
        then sudo dpkg -i cdh4-repository_1.0_all.deb; 
   fi

install:
  - python setup.py install
# command to run tests
script: 
  - python test/all_tests.py
