jdk: 
- oraclejdk7

env:
  global: 
    secure: d1kOuK3dSEs2nNZdGFNcY9KLI5PuWOv7xq9V1b+/+rzhi/BezsvEAjRw+7SeVa/sBk5LcKuKtW06Mjst0npXk487TpQpuLSNzUbX1aaTw4+oG0iJWKeK559iiMs+MBSFYvC6XPts5DkNM+hn5KmhuzCTHBotCv7ZB9Zmuj/ULsg=
  matrix:
  - HADOOPVERSION=2.2.0 HDFS_BACKEND=native
  - HADOOPVERSION=2.2.0 HDFS_BACKEND=jpype-bridged

python:
- "2.7"

before_install:
- sudo apt-get install build-essential python-all-dev libssl-dev
- if [[ $HDFS_BACKEND == "jpype-bridged"  ]]; then wget http://downloads.sourceforge.net/project/jpype/JPype/0.5.4/JPype-0.5.4.2.zip?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fjpype%2Ffiles%2F&ts=1415895636&use_mirror=garr; unzip JPype-0.5.4.2.zip; cd JPype-0.5.4.2; python setup.py install --user; fi
- ssh-keygen -t dsa -P '' -f ~/.ssh/id_dsa
- cat ~/.ssh/id_dsa.pub >> ~/.ssh/authorized_keys
- echo NoHostAuthenticationForLocalhost=yes >> ~/.ssh/config
- sudo groupadd admin
- sudo usermod  -a -G admin $USER
- groups $USER
- . .travis/install_hadoop.sh

install:
- python setup.py build --hdfs-core-impl $HDFS_BACKEND
- python setup.py install --skip-build

script:
- cd test;
- python all_tests.py
- cd ../examples
- ./run_all
language: python
