jdk: 
- oraclejdk7
after_success: 
- #sudo apt-get install debhelper python-all-dev libboost-python-dev libssl-dev python-sphinx devscripts inkscape
- #make debian
- #cd sandbox
- #python -c "import smtplib, glob;from email.mime.application import MIMEApplication;from email.mime.multipart import MIMEMultipart;from email.mime.text import MIMEText;fromaddr = 'travis.ci.rs4@gmail.com';toaddrs  = 'travis.ci.rs4@gmail.com';msg = MIMEMultipart();msg['Subject'] = 'New pydoop deb for $HADOOPVERSION build:$TRAVIS_BUILD_NUMBER';msg['From'] = 'travis.ci.rs4@gmail.com';msg['To'] = 'travis.ci.rs4@gmail.com';username = 'travis.ci.rs4';password = '$pw';part = MIMEText(msg['Subject']);msg.attach(part);deb_file_name = glob.glob('*.deb')[0];part = MIMEApplication(open(deb_file_name,'rb').read());part.add_header('Content-Disposition', 'attachment', filename=deb_file_name);msg.attach(part);server = smtplib.SMTP('smtp.gmail.com:587');server.starttls();server.login(username,password);server.sendmail(msg['From'], msg['To'], msg.as_string());server.quit()"
env: 
  global: 
    secure: d1kOuK3dSEs2nNZdGFNcY9KLI5PuWOv7xq9V1b+/+rzhi/BezsvEAjRw+7SeVa/sBk5LcKuKtW06Mjst0npXk487TpQpuLSNzUbX1aaTw4+oG0iJWKeK559iiMs+MBSFYvC6XPts5DkNM+hn5KmhuzCTHBotCv7ZB9Zmuj/ULsg=
  matrix: 
  - HADOOPVERSION=0.20.2
  - #HADOOPVERSION=cdh3u4
  - #HADOOPVERSION=cdh3u5
  - #HADOOPVERSION=1.0.4
  - #HADOOPVERSION=1.1.2
  - #HADOOPVERSION=1.2.1
  - HADOOPVERSION=2.2.0
  - #HADOOPVERSION=cdh4.2.0
  - HADOOPVERSION=cdh4.3.0
  - HADOOPVERSION=cdh4.3.0 YARN=true
  - #HADOOPVERSION=cdh4.4.0
  - #HADOOPVERSION=cdh4.5.0
python: 
- "2.7"
install:
- export LD_PRELOAD=/lib/x86_64-linux-gnu/libssl.so.1.0.0
- python setup.py install
before_install: 
- sudo apt-get install build-essential python-all-dev libboost-python-dev libssl-dev
- ssh-keygen -t dsa -P '' -f ~/.ssh/id_dsa
- cat ~/.ssh/id_dsa.pub >> ~/.ssh/authorized_keys
- echo NoHostAuthenticationForLocalhost=yes >> ~/.ssh/config
- sudo groupadd admin
- sudo usermod  -a -G admin $USER
- groups $USER
- . .travis_install_hadoop.sh $HADOOPVERSION

script:
- sudo jps
- #export HADOOP_MAPRED_HOME=/usr/lib/hadoop-mapreduce/ 
- #python test/all_tests.py
- cd examples
- ./run_all
- cd ../
language: python
