language: python

python:
 - "2.7"
 - "3.6"

env:
  - HADOOP_MAJOR_VERSION=2 CHECKS=base
  - HADOOP_MAJOR_VERSION=3 CHECKS=base
  - HADOOP_MAJOR_VERSION=2 CHECKS=extras
  - HADOOP_MAJOR_VERSION=3 CHECKS=extras

sudo: required

services: docker

before_install: pip install flake8

# skip installation, requirements are handled in the Docker image
install: true

before_script:
  - flake8 -v .
  - DEBUG=true ./.travis/check_script_template -v

script:
 - docker build --build-arg HADOOP_MAJOR_VERSION=${HADOOP_MAJOR_VERSION} -t crs4/pydoop .
 - docker run --name pydoop -d crs4/pydoop
 - "docker exec pydoop bash -c 'while : ; do jps | grep DataNode && break; done'"
 - DEBUG=true ./.travis/run_checks
 - docker stop pydoop
 - docker rm pydoop
 - if [ "${CHECKS}" = "extras" ]; then docker build -t crs4/pydoop-docs -f Dockerfile.docs .; fi

deploy:
  provider: script
  script: .travis/deploy
  on:
    python: "3.6"
    condition: $CHECKS = base
    repo: crs4/pydoop
    tags: true
